import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

/**
 * Vite 8（Rolldown）的 lib 模式不会应用 output.banner，
 * 这里用插件在产物生成后补回插件头部注释。
 */
function bannerPlugin(text: string): Plugin {
	return {
		name: "mikansei-banner",
		enforce: "post",
		generateBundle(_options, bundle) {
			for (const chunk of Object.values(bundle)) {
				if (chunk.type === "chunk") {
					chunk.code = text + chunk.code;
				}
			}
		},
	};
}

/**
 * 把 manifest.json 复制进构建产物目录，使 dist/ 成为可直接使用的插件目录。
 */
function copyManifest(): Plugin {
	return {
		name: "mikansei-copy-manifest",
		enforce: "post",
		generateBundle() {
			this.emitFile({
				type: "asset",
				fileName: "manifest.json",
				source: readFileSync(
					resolve(import.meta.dirname, "manifest.json"),
					"utf8"
				),
			});
		},
	};
}

export default defineConfig(({ mode }) => {
	const prod = mode === "production";
	return {
		plugins: [react(), bannerPlugin(banner), copyManifest()],
		resolve: {
			alias: [
				{
					find: /^src\//,
					replacement: resolve(import.meta.dirname, "src") + "/",
				},
			],
		},
		build: {
			lib: {
				entry: resolve(import.meta.dirname, "src/main.ts"),
				formats: ["cjs"],
				fileName: () => "main.js",
				cssFileName: "styles",
			},
			outDir: "dist",
			emptyOutDir: true,
			target: "es2018",
			minify: prod ? "oxc" : false,
			sourcemap: prod ? false : "inline",
			cssCodeSplit: false,
			rolldownOptions: {
				external: [
					"obsidian",
					"electron",
					/^@codemirror\//,
					/^@lezer\//,
					...builtins,
				],
				output: {
					entryFileNames: "main.js",
					assetFileNames: "styles.[ext]",
				},
			},
		},
	};
});
